name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: npm ci
      - run: npm test
      - run: git config --global user.name 'Release bot'
      - run: git config --global user.email 'sarat1669+release@gmail.com'
      - name: Commit release
        run: npm version patch -m "[RELEASE] %s"
      - name: Push
        run: git push
